# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firstpass_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_delete_user_user_delete(self) -> None:
        """Test case for delete_user_user_delete

        Delete User
        """
        pass

    def test_get_blob_blob_blob_id_get(self) -> None:
        """Test case for get_blob_blob_blob_id_get

        Get Blob
        """
        pass

    def test_get_user_user_get(self) -> None:
        """Test case for get_user_user_get

        Get User
        """
        pass

    def test_post_user_user_post(self) -> None:
        """Test case for post_user_user_post

        Post User
        """
        pass

    def test_put_blob_blob_blob_id_put(self) -> None:
        """Test case for put_blob_blob_blob_id_put

        Put Blob
        """
        pass

    def test_token_token_post(self) -> None:
        """Test case for token_token_post

        Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
