# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firstpass_client.models.blob import Blob

class TestBlob(unittest.TestCase):
    """Blob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Blob:
        """Test Blob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Blob`
        """
        model = Blob()
        if include_optional:
            return Blob(
                blob_id = '',
                blob = bytes(b'blah')
            )
        else:
            return Blob(
        )
        """

    def testBlob(self):
        """Test Blob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
